name: Adds all opened or reopened issues to the backlog.

on:
  issues:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project
        with:
          project-url: https://github.com/igotinfected/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
