name: Build & test android

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_android:
    name: build-and-test-android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/workflows/build-and-test.yml
      with:
        targetFramework: net7.0-android33.0
