name: Build & test iOS 

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_ios:
    name: build-and-test-ios
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/workflows/build-and-test.yml
      with:
        targetFramework: net7.0-ios
