name: Build & test iOS 

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build_and_test_android:
    steps:
    - uses: ./.github/workflows/build-and-test.yml
      with:
        targetFramework: net7.0-ios
