name: Build & test iOS 

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/Burser/**'

jobs:
  build_and_test_ios:
    uses: ./.github/workflows/build-and-test.yml
    with:
      targetFramework: net7.0-ios
